### PR TITLE
Use Http/2 by default in Kiota

### PR DESCRIPTION
**Pull request by dev-tony-hu**
Fix issue https://github.com/microsoft/kiota-http-dotnet/issues/231

### CODE REVIEW

**Review by andrueastman — APPROVED** [review]
Thanks for catching this @dev-tony-hu!

I think you just need to accept the license policy and we should be good to go here.

**Comment by dev-tony-hu** [comment]
> Thanks for catching this @dev-tony-hu!
> 
> I think you just need to accept the license policy and we should be good to go here.

accept

**Comment by dev-tony-hu** [comment]
@microsoft-github-policy-service agree [company="AvePoint"]
Options:
(default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
@microsoft-github-policy-service agree
(when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
@microsoft-github-policy-service agree company="Microsoft"

**Comment by dev-tony-hu** [comment]
@microsoft-github-policy-service agree company="AvePoint"
@microsoft-github-policy-service agree

**Comment by dev-tony-hu** [comment]
@microsoft-github-policy-service agree company="AvePoint"

**Comment by dev-tony-hu** [comment]
> @dev-tony-hu the command you issued was incorrect. Please try again.
> 
> Examples are:
> 
> ```
> @microsoft-github-policy-service agree
> ```
> 
> and
> 
> ```
> @microsoft-github-policy-service agree company="your company"
> ```

@microsoft-github-policy-service agree company="AvePoint"

**Comment by dev-tony-hu** [comment]
@microsoft-github-policy-service agree

**Comment by dev-tony-hu** [comment]
@microsoft-github-policy-service agree company="AvePoint"

**Pull request merged**
